## File generated by the BNF Converter (bnfc 2.9.5).

# Makefile for building the parser and test program.

GHC        = ghc
HAPPY      = happy
HAPPY_OPTS = --array --info --ghc --coerce
ALEX       = alex
ALEX_OPTS  = --ghc

# List of goals not corresponding to file names.

.PHONY : all clean distclean

# Default goal.

all : TestSmol

# Rules for building the parser.

AbsSmol.hs LexSmol.x ParSmol.y PrintSmol.hs TestSmol.hs : smol.cf
	bnfc --haskell smol.cf

%.hs : %.y
	${HAPPY} ${HAPPY_OPTS} $<

%.hs : %.x
	${ALEX} ${ALEX_OPTS} $<

TestSmol : AbsSmol.hs LexSmol.hs ParSmol.hs PrintSmol.hs TestSmol.hs
	${GHC} ${GHC_OPTS} $@

# Rules for cleaning generated files.

clean :
	-rm -f *.hi *.o *.log *.aux *.dvi

distclean : clean
	-rm -f AbsSmol.hs AbsSmol.hs.bak ComposOp.hs ComposOp.hs.bak DocSmol.txt DocSmol.txt.bak ErrM.hs ErrM.hs.bak LayoutSmol.hs LayoutSmol.hs.bak LexSmol.x LexSmol.x.bak ParSmol.y ParSmol.y.bak PrintSmol.hs PrintSmol.hs.bak SkelSmol.hs SkelSmol.hs.bak TestSmol.hs TestSmol.hs.bak XMLSmol.hs XMLSmol.hs.bak ASTSmol.agda ASTSmol.agda.bak ParserSmol.agda ParserSmol.agda.bak IOLib.agda IOLib.agda.bak Main.agda Main.agda.bak smol.dtd smol.dtd.bak TestSmol LexSmol.hs ParSmol.hs ParSmol.info ParDataSmol.hs Makefile


# EOF
